site_name: MkDocs Study

theme:
  name: material
  features:
    - navigation.indexes

nav:
  - Introduction: index.md
  - Topic 1: topic1/index.md

plugins:
  - search:
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      fallback_to_default: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: ja
          name: 日本語
          build: true
          site_name: MkDocs勉強
          nav_translations:
            Introduction: はじめに
            Topic 1: 話題1

extra:
  version:
    provider: mike
  alternate:
    - name: English
      link: ""
      lang: en
    - name: 日本語
      link: ja
      lang: ja

markdown_extensions:
  - admonition
  - pymdownx.details
