name: Build MkDocs with mike and create PR

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  PR_BRANCH: gh-pages-${{ github.run_number }}
  AUTO_COMMIT_USER_NAME: github-actions[bot]
  AUTO_COMMIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  DEFAULT_VERSION_ALIAS: latest

permissions:
  content: write
  pull-requests: write

jobs:
  release-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: setup mkdocs project
        env:
          REF: ${{ github.ref }}
        run: |
          export VER=`echo "${REF##*/}"`
          echo "version=${VER}" >> $GITHUB_ENV
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.name "${{ env.AUTO_COMMIT_USER_NAME }}"
          git config --local user.email "${{ env.AUTO_COMMIT_USER_EMAIL }}"
          git fetch

      - name: make PR_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b ${{ env.PR_BRANCH }} origin/gh-pages
          git push origin ${{ env.PR_BRANCH }}
          git checkout ${{ github.ref }}

      - name: check mike list previous
        continue-on-error: true
        run: |
          uv run mike list --branch ${{ env.PR_BRANCH }} | grep ${{ env.version }}
          if [ $? ]; then
            uv run mike delete --branch ${{ env.PR_BRANCH }} ${{ env.version }}
          fi

      - name: check mike list default version alias
        continue-on-error: true
        run: |
          uv run mike list --branch ${{ env.PR_BRANCH }} | grep ${{ env.DEFAULT_VERSION_ALIAS }}
          if [ $? ]; then
            uv run mike delete --branch ${{ env.PR_BRANCH }} ${{ env.DEFAULT_VERSION_ALIAS }}
          fi

      - name: build mkdocs
        run: |
          uv run mike deploy --branch ${{ env.PR_BRANCH }} ${{ env.version }}
          uv run mike alias --branch ${{ env.PR_BRANCH }} ${{ env.version }} ${{ env.DEFAULT_VERSION_ALIAS }}
          uv run mike set-default --branch ${{ env.PR_BRANCH }} --allow-empty ${{ env.DEFAULT_VERSION_ALIAS }}

      - name: checkout PR_BRANCH
        run: |
          git checkout ${{ env.PR_BRANCH }}

      - name: pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update MkDocs
          committer: GitHub <noreply@github.com>
          author: ${{ env.AUTO_COMMIT_USER_NAME }} <${{ env.AUTO_COMMIT_USER_EMAIL }}>
          signoff: false
          branch: ${{ env.PR_BRANCH }}
          base: gh-pages
          delete-branch: true
          title: 'Update MkDocs'
          body: |
            Update report
          labels: |
            automated pr
          draft: false
